"""cria planos e creditos

Revision ID: 1865dcf75a2e
Revises: acdfe795c74d
Create Date: 2026-07-22 09:05:48.628876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1865dcf75a2e'
down_revision: Union[str, Sequence[str], None] = 'acdfe795c74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('credits_per_cycle', sa.Integer(), nullable=False),
    sa.Column('booking_window_days', sa.Integer(), nullable=False),
    sa.Column('cycle_months', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=True)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('student_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_plans_id'), 'student_plans', ['id'], unique=False)
    op.create_index(op.f('ix_student_plans_plan_id'), 'student_plans', ['plan_id'], unique=False)
    op.create_index(op.f('ix_student_plans_user_id'), 'student_plans', ['user_id'], unique=False)
    op.create_table('credit_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('credits_total', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_plan_id'], ['student_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_plan_id', 'start_date', name='uq_credit_cycle_student_plan_start')
    )
    op.create_index(op.f('ix_credit_cycles_id'), 'credit_cycles', ['id'], unique=False)
    op.create_index(op.f('ix_credit_cycles_student_plan_id'), 'credit_cycles', ['student_plan_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_cycle_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['credit_cycle_id'], ['credit_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_booking_id'), 'credit_transactions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_credit_cycle_id'), 'credit_transactions', ['credit_cycle_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_id'), 'credit_transactions', ['id'], unique=False)
    op.alter_column('bookings', 'booking_type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=False)
    op.alter_column('bookings', 'spots',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_bookings_slot_id'), 'bookings', ['slot_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.drop_constraint(op.f('bookings_coach_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'time')
    op.drop_column('bookings', 'date')
    op.drop_column('bookings', 'coach_id')
    op.alter_column('class_slots', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_class_slots_coach_id'), 'class_slots', ['coach_id'], unique=False)
    op.create_index(op.f('ix_class_slots_date'), 'class_slots', ['date'], unique=False)
    op.alter_column('coaches', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('coaches', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_class_slots_date'), table_name='class_slots')
    op.drop_index(op.f('ix_class_slots_coach_id'), table_name='class_slots')
    op.alter_column('class_slots', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('bookings', sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('bookings_coach_id_fkey'), 'bookings', 'coaches', ['coach_id'], ['id'])
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_slot_id'), table_name='bookings')
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bookings', 'spots',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('bookings', 'booking_type',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'individual'::character varying"),
               nullable=True)
    op.drop_index(op.f('ix_credit_transactions_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_credit_cycle_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_booking_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_credit_cycles_student_plan_id'), table_name='credit_cycles')
    op.drop_index(op.f('ix_credit_cycles_id'), table_name='credit_cycles')
    op.drop_table('credit_cycles')
    op.drop_index(op.f('ix_student_plans_user_id'), table_name='student_plans')
    op.drop_index(op.f('ix_student_plans_plan_id'), table_name='student_plans')
    op.drop_index(op.f('ix_student_plans_id'), table_name='student_plans')
    op.drop_table('student_plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_code'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
